type Category = 'romance' | 'family' | 'career' | 'adventure' | 'life' | 'dreams';

interface Question {
  id: string;
  category: Category;
  text: { en: string; es: string };
  type: 'scale' | 'choice' | 'timeline';
  options?: { en: string[]; es: string[] };
  minLabel?: { en: string; es: string };
  maxLabel?: { en: string; es: string };
}

export const futureForecastQuestions: Question[] = [
  // Romance Category (10 questions)
  { id: 'r1', category: 'romance', type: 'timeline', text: { en: 'When do you see us getting engaged?', es: '¿Cuándo nos vemos comprometidos?' }, minLabel: { en: 'Soon', es: 'Pronto' }, maxLabel: { en: 'In a few years', es: 'En unos años' } },
  { id: 'r2', category: 'romance', type: 'choice', text: { en: 'What type of wedding do you envision?', es: '¿Qué tipo de boda imaginas?' }, options: { en: ['Intimate & small', 'Medium celebration', 'Big & grand', 'Destination wedding'], es: ['Íntima y pequeña', 'Celebración mediana', 'Grande y lujosa', 'Boda destino'] } },
  { id: 'r3', category: 'romance', type: 'scale', text: { en: 'How important are romantic surprises to you?', es: '¿Qué tan importantes son las sorpresas románticas?' }, minLabel: { en: 'Nice to have', es: 'Agradable' }, maxLabel: { en: 'Essential', es: 'Esencial' } },
  { id: 'r4', category: 'romance', type: 'choice', text: { en: 'Perfect date night activity?', es: '¿Actividad perfecta para una cita?' }, options: { en: ['Movie & cuddles', 'Dancing & music', 'Cooking together', 'Outdoor adventure'], es: ['Película y mimos', 'Bailar y música', 'Cocinar juntos', 'Aventura al aire libre'] } },
  { id: 'r5', category: 'romance', type: 'scale', text: { en: 'How often should we say "I love you"?', es: '¿Con qué frecuencia deberíamos decir "te amo"?' }, minLabel: { en: 'Special moments', es: 'Momentos especiales' }, maxLabel: { en: 'Multiple times daily', es: 'Varias veces al día' } },
  { id: 'r6', category: 'romance', type: 'choice', text: { en: 'Dream romantic getaway location?', es: '¿Lugar soñado para escapada romántica?' }, options: { en: ['Beach paradise', 'Mountain retreat', 'European city', 'Tropical island'], es: ['Paraíso playero', 'Retiro montañoso', 'Ciudad europea', 'Isla tropical'] } },
  { id: 'r7', category: 'romance', type: 'scale', text: { en: 'How important are couple traditions to you?', es: '¿Qué tan importantes son las tradiciones de pareja?' }, minLabel: { en: 'Flexible', es: 'Flexible' }, maxLabel: { en: 'Very important', es: 'Muy importante' } },
  { id: 'r8', category: 'romance', type: 'timeline', text: { en: 'When should we renew our vows?', es: '¿Cuándo deberíamos renovar nuestros votos?' }, minLabel: { en: '5 years', es: '5 años' }, maxLabel: { en: '25+ years', es: '25+ años' } },
  { id: 'r9', category: 'romance', type: 'choice', text: { en: 'How should we celebrate Valentine\'s Day?', es: '¿Cómo deberíamos celebrar San Valentín?' }, options: { en: ['Skip it/casual', 'Nice dinner out', 'Big romantic gesture', 'Weekend getaway'], es: ['Omitir/casual', 'Buena cena fuera', 'Gran gesto romántico', 'Escapada de fin de semana'] } },
  { id: 'r10', category: 'romance', type: 'scale', text: { en: 'How much should we prioritize couple time vs. social time?', es: '¿Cuánto priorizar tiempo de pareja vs. social?' }, minLabel: { en: 'Balanced', es: 'Equilibrado' }, maxLabel: { en: 'Couple first', es: 'Pareja primero' } },
  
  // Family Category (10 questions)
  { id: 'f1', category: 'family', type: 'choice', text: { en: 'How many kids do you want?', es: '¿Cuántos hijos quieres?' }, options: { en: ['None', '1-2 kids', '3-4 kids', '5+ kids'], es: ['Ninguno', '1-2 hijos', '3-4 hijos', '5+ hijos'] } },
  { id: 'f2', category: 'family', type: 'timeline', text: { en: 'When should we start trying for our first child?', es: '¿Cuándo deberíamos intentar tener nuestro primer hijo?' }, minLabel: { en: 'Soon', es: 'Pronto' }, maxLabel: { en: 'In 5+ years', es: 'En 5+ años' } },
  { id: 'f3', category: 'family', type: 'scale', text: { en: 'How close should we live to extended family?', es: '¿Qué tan cerca vivir de la familia extendida?' }, minLabel: { en: 'Far/independent', es: 'Lejos/independiente' }, maxLabel: { en: 'Same city/close', es: 'Misma ciudad/cerca' } },
  { id: 'f4', category: 'family', type: 'choice', text: { en: 'Ideal parenting style?', es: '¿Estilo de crianza ideal?' }, options: { en: ['Relaxed/flexible', 'Structured routine', 'Mix of both', 'Child-led'], es: ['Relajado/flexible', 'Rutina estructurada', 'Mezcla de ambos', 'Guiado por niño'] } },
  { id: 'f5', category: 'family', type: 'scale', text: { en: 'How important are family traditions and rituals?', es: '¿Qué tan importantes son las tradiciones familiares?' }, minLabel: { en: 'Flexible', es: 'Flexible' }, maxLabel: { en: 'Essential', es: 'Esencial' } },
  { id: 'f6', category: 'family', type: 'choice', text: { en: 'Ideal family vacation style?', es: '¿Estilo ideal de vacaciones familiares?' }, options: { en: ['Relaxing beach', 'Adventure trips', 'Cultural cities', 'Stay-cations'], es: ['Playa relajante', 'Viajes de aventura', 'Ciudades culturales', 'Vacaciones en casa'] } },
  { id: 'f7', category: 'family', type: 'scale', text: { en: 'How important is having pets in our family?', es: '¿Qué tan importante es tener mascotas?' }, minLabel: { en: 'Not important', es: 'No importante' }, maxLabel: { en: 'Must have', es: 'Debe tener' } },
  { id: 'f8', category: 'family', type: 'choice', text: { en: 'How should we divide household responsibilities?', es: '¿Cómo dividir responsabilidades del hogar?' }, options: { en: ['Equal split', 'By preference', 'Hire help', 'Flexible/rotating'], es: ['División igual', 'Por preferencia', 'Contratar ayuda', 'Flexible/rotativo'] } },
  { id: 'f9', category: 'family', type: 'scale', text: { en: 'How important is work-life balance for our family?', es: '¿Qué tan importante es el equilibrio trabajo-vida?' }, minLabel: { en: 'Career focused', es: 'Enfocado en carrera' }, maxLabel: { en: 'Balance is key', es: 'Equilibrio es clave' } },
  { id: 'f10', category: 'family', type: 'timeline', text: { en: 'When should we buy our family home?', es: '¿Cuándo deberíamos comprar nuestra casa familiar?' }, minLabel: { en: 'Before kids', es: 'Antes de hijos' }, maxLabel: { en: 'After kids grow', es: 'Después que crezcan' } },

  // Career Category (10 questions)
  { id: 'c1', category: 'career', type: 'scale', text: { en: 'How important is career success vs. personal happiness?', es: '¿Qué tan importante es el éxito profesional vs. felicidad?' }, minLabel: { en: 'Happiness first', es: 'Felicidad primero' }, maxLabel: { en: 'Career success', es: 'Éxito profesional' } },
  { id: 'c2', category: 'career', type: 'choice', text: { en: 'Would you relocate for a career opportunity?', es: '¿Te mudarías por una oportunidad laboral?' }, options: { en: ['Absolutely', 'Only if mutual', 'Prefer not to', 'Never'], es: ['Absolutamente', 'Solo si es mutuo', 'Prefiero no', 'Nunca'] } },
  { id: 'c3', category: 'career', type: 'timeline', text: { en: 'When do you want to retire?', es: '¿Cuándo quieres retirarte?' }, minLabel: { en: 'Early (50s)', es: 'Temprano (50s)' }, maxLabel: { en: 'Traditional (65+)', es: 'Tradicional (65+)' } },
  { id: 'c4', category: 'career', type: 'scale', text: { en: 'How much should we prioritize building wealth?', es: '¿Cuánto priorizar construir riqueza?' }, minLabel: { en: 'Live comfortably', es: 'Vivir cómodo' }, maxLabel: { en: 'Maximum wealth', es: 'Máxima riqueza' } },
  { id: 'c5', category: 'family', type: 'choice', text: { en: 'Should one partner stay home with kids?', es: '¿Debería uno quedarse en casa con los niños?' }, options: { en: ['Both work', 'One stays home', 'Flexible/part-time', 'Depends on situation'], es: ['Ambos trabajan', 'Uno se queda', 'Flexible/medio tiempo', 'Depende situación'] } },
  { id: 'c6', category: 'career', type: 'scale', text: { en: 'How important is having separate vs. joint finances?', es: '¿Qué tan importante tener finanzas separadas vs. conjuntas?' }, minLabel: { en: 'Fully joint', es: 'Totalmente conjunto' }, maxLabel: { en: 'Mostly separate', es: 'Mayormente separado' } },
  { id: 'c7', category: 'career', type: 'choice', text: { en: 'Would you support a partner starting a business?', es: '¿Apoyarías a tu pareja iniciando un negocio?' }, options: { en: ['Fully support', 'Support with plan', 'Cautious support', 'Prefer stable job'], es: ['Apoyo total', 'Apoyo con plan', 'Apoyo cauteloso', 'Prefiero trabajo estable'] } },
  { id: 'c8', category: 'career', type: 'scale', text: { en: 'How important is having an emergency fund?', es: '¿Qué tan importante es tener fondo de emergencia?' }, minLabel: { en: 'Nice to have', es: 'Bueno tener' }, maxLabel: { en: 'Must have', es: 'Debe tener' } },
  { id: 'c9', category: 'career', type: 'timeline', text: { en: 'When should we have our finances fully merged?', es: '¿Cuándo fusionar completamente nuestras finanzas?' }, minLabel: { en: 'Before marriage', es: 'Antes del matrimonio' }, maxLabel: { en: 'After years together', es: 'Después de años juntos' } },
  { id: 'c10', category: 'career', type: 'scale', text: { en: 'How much should we save vs. enjoy now?', es: '¿Cuánto ahorrar vs. disfrutar ahora?' }, minLabel: { en: 'Enjoy life now', es: 'Disfrutar ahora' }, maxLabel: { en: 'Save for future', es: 'Ahorrar para futuro' } },

  // Adventure Category (10 questions)
  { id: 'a1', category: 'adventure', type: 'choice', text: { en: 'Dream vacation destination?', es: '¿Destino de vacaciones soñado?' }, options: { en: ['Tropical paradise', 'European adventure', 'Asian exploration', 'African safari'], es: ['Paraíso tropical', 'Aventura europea', 'Exploración asiática', 'Safari africano'] } },
  { id: 'a2', category: 'adventure', type: 'scale', text: { en: 'How often should we travel internationally?', es: '¿Con qué frecuencia viajar internacionalmente?' }, minLabel: { en: 'Rarely', es: 'Rara vez' }, maxLabel: { en: 'Multiple times/year', es: 'Varias veces/año' } },
  { id: 'a3', category: 'adventure', type: 'choice', text: { en: 'Preferred travel style?', es: '¿Estilo de viaje preferido?' }, options: { en: ['Luxury & comfort', 'Mid-range comfort', 'Budget backpacking', 'Mix based on trip'], es: ['Lujo y comodidad', 'Comodidad media', 'Mochilero económico', 'Mezcla según viaje'] } },
  { id: 'a4', category: 'adventure', type: 'scale', text: { en: 'How adventurous should our trips be?', es: '¿Qué tan aventureros deben ser nuestros viajes?' }, minLabel: { en: 'Relaxing & safe', es: 'Relajante y seguro' }, maxLabel: { en: 'Extreme & thrilling', es: 'Extremo y emocionante' } },
  { id: 'a5', category: 'adventure', type: 'choice', text: { en: 'Would you try extreme sports together?', es: '¿Probarían deportes extremos juntos?' }, options: { en: ['Absolutely!', 'Some activities', 'Watch only', 'No thanks'], es: ['¡Absolutamente!', 'Algunas actividades', 'Solo mirar', 'No gracias'] } },
  { id: 'a6', category: 'adventure', type: 'scale', text: { en: 'How important is traveling before having kids?', es: '¿Qué tan importante es viajar antes de tener hijos?' }, minLabel: { en: 'Not crucial', es: 'No crucial' }, maxLabel: { en: 'Very important', es: 'Muy importante' } },
  { id: 'a7', category: 'adventure', type: 'choice', text: { en: 'Would you live abroad for a year?', es: '¿Vivirían en el extranjero por un año?' }, options: { en: ['Yes, absolutely', 'Maybe someday', 'Prefer not to', 'Never'], es: ['Sí, absolutamente', 'Quizás algún día', 'Prefiero no', 'Nunca'] } },
  { id: 'a8', category: 'adventure', type: 'scale', text: { en: 'How important is trying new cuisines together?', es: '¿Qué tan importante es probar nuevas cocinas juntos?' }, minLabel: { en: 'Stick to familiar', es: 'Familiar' }, maxLabel: { en: 'Always adventurous', es: 'Siempre aventurero' } },
  { id: 'a9', category: 'adventure', type: 'choice', text: { en: 'Preferred outdoor activity together?', es: '¿Actividad al aire libre preferida juntos?' }, options: { en: ['Hiking & camping', 'Beach & water sports', 'Skiing & snow', 'City exploring'], es: ['Senderismo y camping', 'Playa y deportes acuáticos', 'Esquí y nieve', 'Explorar ciudades'] } },
  { id: 'a10', category: 'adventure', type: 'scale', text: { en: 'How much spontaneity vs. planning for trips?', es: '¿Cuánta espontaneidad vs. planificación en viajes?' }, minLabel: { en: 'Plan everything', es: 'Planear todo' }, maxLabel: { en: 'Go with flow', es: 'Ir con la corriente' } },

  // Life Goals Category (10 questions)
  { id: 'l1', category: 'life', type: 'choice', text: { en: 'Where do you see us living long-term?', es: '¿Dónde nos ves viviendo a largo plazo?' }, options: { en: ['Big city', 'Suburbs', 'Small town', 'Countryside'], es: ['Gran ciudad', 'Suburbios', 'Pueblo pequeño', 'Campo'] } },
  { id: 'l2', category: 'life', type: 'scale', text: { en: 'How important is owning vs. renting?', es: '¿Qué tan importante es comprar vs. rentar?' }, minLabel: { en: 'Renting is fine', es: 'Rentar está bien' }, maxLabel: { en: 'Must own', es: 'Debe comprar' } },
  { id: 'l3', category: 'life', type: 'timeline', text: { en: 'When should we buy our dream home?', es: '¿Cuándo comprar nuestra casa soñada?' }, minLabel: { en: 'In 2-3 years', es: 'En 2-3 años' }, maxLabel: { en: 'In 10+ years', es: 'En 10+ años' } },
  { id: 'l4', category: 'life', type: 'choice', text: { en: 'Ideal home type?', es: '¿Tipo de casa ideal?' }, options: { en: ['Modern apartment', 'Classic house', 'Farmhouse', 'Eco-friendly home'], es: ['Apartamento moderno', 'Casa clásica', 'Casa de campo', 'Casa ecológica'] } },
  { id: 'l5', category: 'life', type: 'scale', text: { en: 'How important is environmental sustainability to us?', es: '¿Qué tan importante es la sostenibilidad ambiental?' }, minLabel: { en: 'Moderate effort', es: 'Esfuerzo moderado' }, maxLabel: { en: 'Top priority', es: 'Máxima prioridad' } },
  { id: 'l6', category: 'life', type: 'choice', text: { en: 'How should we spend our golden years?', es: '¿Cómo pasar nuestros años dorados?' }, options: { en: ['Travel the world', 'Close to family', 'Quiet retirement', 'Active community'], es: ['Viajar el mundo', 'Cerca de familia', 'Jubilación tranquila', 'Comunidad activa'] } },
  { id: 'l7', category: 'life', type: 'scale', text: { en: 'How important is maintaining close friendships?', es: '¿Qué tan importante mantener amistades cercanas?' }, minLabel: { en: 'Couple focused', es: 'Enfocado en pareja' }, maxLabel: { en: 'Very important', es: 'Muy importante' } },
  { id: 'l8', category: 'life', type: 'choice', text: { en: 'Approach to health and fitness?', es: '¿Enfoque para salud y fitness?' }, options: { en: ['Very active lifestyle', 'Moderate exercise', 'Casual activities', 'Flexible approach'], es: ['Estilo muy activo', 'Ejercicio moderado', 'Actividades casuales', 'Enfoque flexible'] } },
  { id: 'l9', category: 'life', type: 'scale', text: { en: 'How much should we invest in self-improvement?', es: '¿Cuánto invertir en auto-mejora?' }, minLabel: { en: 'Natural growth', es: 'Crecimiento natural' }, maxLabel: { en: 'Constant learning', es: 'Aprendizaje constante' } },
  { id: 'l10', category: 'life', type: 'scale', text: { en: 'How important is leaving a legacy?', es: '¿Qué tan importante es dejar un legado?' }, minLabel: { en: 'Live for now', es: 'Vivir el ahora' }, maxLabel: { en: 'Very important', es: 'Muy importante' } },

  // Dreams Category (10 questions)
  { id: 'd1', category: 'dreams', type: 'choice', text: { en: 'What\'s your wildest dream for us?', es: '¿Cuál es tu sueño más salvaje para nosotros?' }, options: { en: ['Build empire together', 'Travel the world', 'Big family', 'Change the world'], es: ['Construir imperio juntos', 'Viajar el mundo', 'Familia grande', 'Cambiar el mundo'] } },
  { id: 'd2', category: 'dreams', type: 'scale', text: { en: 'How important is achieving fame or recognition?', es: '¿Qué tan importante es lograr fama o reconocimiento?' }, minLabel: { en: 'Not important', es: 'No importante' }, maxLabel: { en: 'Major goal', es: 'Meta importante' } },
  { id: 'd3', category: 'dreams', type: 'timeline', text: { en: 'When should we start our passion project together?', es: '¿Cuándo empezar nuestro proyecto de pasión juntos?' }, minLabel: { en: 'This year', es: 'Este año' }, maxLabel: { en: 'In retirement', es: 'En jubilación' } },
  { id: 'd4', category: 'dreams', type: 'choice', text: { en: 'If money wasn\'t an issue, what would you do?', es: 'Si el dinero no fuera problema, ¿qué harías?' }, options: { en: ['Build dream house', 'Start foundation', 'Travel forever', 'Pursue art/passion'], es: ['Construir casa soñada', 'Iniciar fundación', 'Viajar para siempre', 'Perseguir arte/pasión'] } },
  { id: 'd5', category: 'dreams', type: 'scale', text: { en: 'How much should we sacrifice for our dreams?', es: '¿Cuánto sacrificar por nuestros sueños?' }, minLabel: { en: 'Be practical', es: 'Ser práctico' }, maxLabel: { en: 'Go all in', es: 'Ir con todo' } },
  { id: 'd6', category: 'dreams', type: 'choice', text: { en: 'Would you pursue a creative career later in life?', es: '¿Perseguirías carrera creativa más adelante?' }, options: { en: ['Absolutely', 'Maybe as hobby', 'Probably not', 'Already doing it'], es: ['Absolutamente', 'Quizás como hobby', 'Probablemente no', 'Ya lo hago'] } },
  { id: 'd7', category: 'dreams', type: 'scale', text: { en: 'How important is living an extraordinary life?', es: '¿Qué tan importante es vivir una vida extraordinaria?' }, minLabel: { en: 'Simple is good', es: 'Simple es bueno' }, maxLabel: { en: 'Must be epic', es: 'Debe ser épico' } },
  { id: 'd8', category: 'dreams', type: 'choice', text: { en: 'What type of adventure would you take a year for?', es: '¿Qué aventura tomarías por un año?' }, options: { en: ['Sail around world', 'Live in another country', 'Build something big', 'Spiritual journey'], es: ['Navegar el mundo', 'Vivir en otro país', 'Construir algo grande', 'Viaje espiritual'] } },
  { id: 'd9', category: 'dreams', type: 'scale', text: { en: 'How much risk should we take for dreams?', es: '¿Cuánto riesgo tomar por sueños?' }, minLabel: { en: 'Play it safe', es: 'Jugar seguro' }, maxLabel: { en: 'Big risks', es: 'Grandes riesgos' } },
  { id: 'd10', category: 'dreams', type: 'scale', text: { en: 'How important is personal growth vs. stability?', es: '¿Qué tan importante es crecimiento personal vs. estabilidad?' }, minLabel: { en: 'Stability', es: 'Estabilidad' }, maxLabel: { en: 'Growth', es: 'Crecimiento' } },
];
