// Saying I Do - Pre-Marriage Devotional Series
// 22 devotionals for couples preparing for marriage

export interface BilingualText {
  en: string;
  es: string;
}

export interface SayingIDoEntry {
  day: number;
  title: BilingualText;
  scriptureAnchor: BilingualText;
  exposition: BilingualText;
  realityCheck: BilingualText;
  practicalImplications: BilingualText;
  closingCharge: BilingualText;
  reflectionQuestions: BilingualText[];
  practiceBox: BilingualText[];
}

export const sayingIDoEntries: SayingIDoEntry[] = [
  {
    day: 1,
    title: {
      en: "Marriage Is Public",
      es: "El Matrimonio Es Público"
    },
    scriptureAnchor: {
      en: "\"Therefore what God has joined together, let no one separate.\" — Mark 10:9\n\n\"You are witnesses today that I have bought… Ruth the Moabite… as my wife.\" — Ruth 4:9–10",
      es: "\"Por tanto, lo que Dios juntó, no lo separe el hombre.\" — Marcos 10:9\n\n\"Vosotros sois testigos hoy de que yo he comprado... a Rut la moabita... para que sea mi esposa.\" — Rut 4:9–10"
    },
    exposition: {
      en: "Marriage is not a secret romance hidden away from the world. It is not merely a private arrangement between two consenting adults who happen to love each other. From the very beginning of Scripture, marriage has been understood as a covenant—a sacred, binding agreement made not only between two people but before God Himself and in the presence of witnesses.\n\nWhen God brought Eve to Adam in the Garden of Eden, it was the first wedding—and God Himself was the witness. Throughout the Old Testament, covenants were always public affairs. They were sealed with witnesses, marked by ceremonies, and recorded for posterity. When Boaz declared his intention to marry Ruth, he did so at the city gate before the elders of the community. \"You are witnesses today,\" he proclaimed (Ruth 4:9). This was not a formality—it was essential to the covenant itself.\n\nWhy does Scripture insist on the public nature of marriage? Because covenants carry weight. A promise made in secret can be broken in secret. But a vow spoken before God and community carries accountability that reaches beyond the couple themselves. The witnesses are not merely spectators; they are participants in upholding the covenant. They are called to encourage, support, and when necessary, admonish the couple to keep their vows.\n\nJesus reinforced this understanding when He declared, \"What God has joined together, let no one separate\" (Mark 10:9). Notice the language: God joins. This is not merely a human arrangement subject to human revision. Marriage is a divine work, and because it is divine, it must be honored publicly. The community of faith has a responsibility to protect, nurture, and celebrate marriages precisely because they reflect God's covenant love for His people.\n\nThe public nature of marriage also serves as a testimony. Your union declares something to the watching world. It says that love is not merely a feeling but a commitment. It proclaims that two people have chosen to bind their lives together under God's authority. It witnesses to the reality of covenant faithfulness in a world drowning in broken promises and casual relationships.\n\nWhen you stand before your community and say \"I do,\" you are not simply expressing your feelings. You are making a declaration before God and witnesses that you will love, honor, and cherish each other for life. This is why the wedding ceremony matters. It is not a performance or a party; it is a covenant-making event that establishes your marriage on a foundation of accountability and community support.",
      es: "El matrimonio no es un romance secreto escondido del mundo. No es simplemente un acuerdo privado entre dos adultos que consienten y que resulta que se aman. Desde el principio mismo de las Escrituras, el matrimonio se ha entendido como un pacto—un acuerdo sagrado y vinculante hecho no solo entre dos personas, sino ante Dios mismo y en presencia de testigos.\n\nCuando Dios trajo a Eva a Adán en el Jardín del Edén, fue la primera boda—y Dios mismo fue el testigo. A lo largo del Antiguo Testamento, los pactos siempre fueron asuntos públicos. Fueron sellados con testigos, marcados por ceremonias y registrados para la posteridad. Cuando Booz declaró su intención de casarse con Rut, lo hizo en la puerta de la ciudad ante los ancianos de la comunidad. \"Vosotros sois testigos hoy,\" proclamó (Rut 4:9). Esto no era una formalidad—era esencial para el pacto mismo.\n\n¿Por qué las Escrituras insisten en la naturaleza pública del matrimonio? Porque los pactos tienen peso. Una promesa hecha en secreto puede romperse en secreto. Pero un voto pronunciado ante Dios y la comunidad conlleva una responsabilidad que va más allá de la pareja misma. Los testigos no son meros espectadores; son participantes en mantener el pacto. Están llamados a animar, apoyar y, cuando sea necesario, amonestar a la pareja para que cumplan sus votos.\n\nJesús reforzó este entendimiento cuando declaró: \"Lo que Dios juntó, no lo separe el hombre\" (Marcos 10:9). Nota el lenguaje: Dios une. Esto no es meramente un arreglo humano sujeto a revisión humana. El matrimonio es una obra divina, y porque es divina, debe ser honrada públicamente. La comunidad de fe tiene la responsabilidad de proteger, nutrir y celebrar los matrimonios precisamente porque reflejan el amor de pacto de Dios por Su pueblo.\n\nLa naturaleza pública del matrimonio también sirve como testimonio. Su unión declara algo al mundo que observa. Dice que el amor no es meramente un sentimiento sino un compromiso. Proclama que dos personas han elegido unir sus vidas bajo la autoridad de Dios. Testifica la realidad de la fidelidad del pacto en un mundo que se ahoga en promesas rotas y relaciones casuales.\n\nCuando te paras ante tu comunidad y dices \"Acepto,\" no estás simplemente expresando tus sentimientos. Estás haciendo una declaración ante Dios y testigos de que amarás, honrarás y apreciarás al otro de por vida. Es por eso que la ceremonia de boda importa. No es una actuación o una fiesta; es un evento de creación de pacto que establece tu matrimonio sobre un fundamento de responsabilidad y apoyo comunitario."
    },
    realityCheck: {
      en: "Our culture has done everything possible to privatize relationships. We are told that what happens between two consenting adults is nobody's business. We are encouraged to keep our relationships hidden until we are ready to go public—and even then, the public declaration is optional. Cohabitation has replaced covenant. \"We don't need a piece of paper\" has become the anthem of a generation that fears commitment and rejects accountability.\n\nBut Scripture confronts this lie head-on. Marriage is not private. Marriage is public, accountable, and witnessed. To treat marriage as a secret arrangement is to strip it of its covenantal weight. It is to reduce the most sacred human relationship to a mere contractual exchange that can be terminated when feelings fade.\n\nThe privatization of marriage has devastating consequences. When relationships exist in secret, there is no one to challenge unhealthy patterns. There is no one to encourage faithfulness during difficult seasons. There is no one to hold the couple accountable when they begin to drift. The result is a generation of broken relationships and shattered families.\n\nMoreover, the rejection of public marriage is often rooted in a desire to keep one's options open. If no one knows about our commitment, we can walk away without explanation. If we haven't made vows before witnesses, we can rewrite our story however we choose. This is not love—it is cowardice dressed up as freedom.\n\nGod's design for marriage includes community. The couple does not stand alone. They are surrounded by a cloud of witnesses who have seen their covenant and who will help them keep it. To reject this design is to reject God's wisdom and to invite disaster into your relationship.",
      es: "Nuestra cultura ha hecho todo lo posible para privatizar las relaciones. Se nos dice que lo que sucede entre dos adultos que consienten no es asunto de nadie. Se nos anima a mantener nuestras relaciones ocultas hasta que estemos listos para hacerlas públicas—y aun entonces, la declaración pública es opcional. La cohabitación ha reemplazado al pacto. \"No necesitamos un papel\" se ha convertido en el himno de una generación que teme el compromiso y rechaza la responsabilidad.\n\nPero las Escrituras confrontan esta mentira de frente. El matrimonio no es privado. El matrimonio es público, responsable y con testigos. Tratar el matrimonio como un arreglo secreto es despojarlo de su peso de pacto. Es reducir la relación humana más sagrada a un mero intercambio contractual que puede terminarse cuando los sentimientos se desvanecen.\n\nLa privatización del matrimonio tiene consecuencias devastadoras. Cuando las relaciones existen en secreto, no hay nadie para desafiar patrones insalubres. No hay nadie para alentar la fidelidad durante temporadas difíciles. No hay nadie para responsabilizar a la pareja cuando comienzan a desviarse. El resultado es una generación de relaciones rotas y familias destrozadas.\n\nAdemás, el rechazo del matrimonio público a menudo está arraigado en un deseo de mantener las opciones abiertas. Si nadie sabe de nuestro compromiso, podemos marcharnos sin explicación. Si no hemos hecho votos ante testigos, podemos reescribir nuestra historia como queramos. Esto no es amor—es cobardía disfrazada de libertad.\n\nEl diseño de Dios para el matrimonio incluye comunidad. La pareja no está sola. Están rodeados por una nube de testigos que han visto su pacto y que les ayudarán a mantenerlo. Rechazar este diseño es rechazar la sabiduría de Dios e invitar el desastre a tu relación."
    },
    practicalImplications: {
      en: "If marriage is public, then your journey toward marriage must also involve others. This begins now—before the wedding day. Couples preparing for marriage must intentionally invite mentors, family members, and their faith community into their relationship.\n\nFirst, find a mature couple or mentor who can walk with you through your engagement. This should be someone who knows you well enough to ask hard questions and who loves you enough to tell you the truth. They should have access to your relationship—not just the polished version you present on social media, but the real struggles, fears, and challenges you face.\n\nSecond, involve your families. Yes, you are adults. Yes, you will make your own decisions. But God has placed family in your life for a reason. Honor your parents by seeking their input and blessing. Even if your family situation is complicated, find ways to include them in your journey.\n\nThird, be connected to a local church. Marriage is not just between two people—it is between two people and their community. Your church will pray for you, counsel you, celebrate with you, and support you through the inevitable difficulties of married life. If you are not connected to a church, find one now. Do not enter marriage without a faith community to support you.\n\nFourth, be intentional about your wedding ceremony. This is not merely a party—it is a covenant-making event. Choose a ceremony that reflects the seriousness of your vows. Invite witnesses who will hold you accountable. Make your promises before God and your community with full awareness of what you are doing.\n\nFinally, continue to live publicly after the wedding. Don't disappear into your new life together and neglect the relationships that supported you. Stay connected. Stay accountable. Let your marriage be a testimony to God's faithfulness.",
      es: "Si el matrimonio es público, entonces tu camino hacia el matrimonio también debe involucrar a otros. Esto comienza ahora—antes del día de la boda. Las parejas que se preparan para el matrimonio deben invitar intencionalmente a mentores, miembros de la familia y su comunidad de fe a su relación.\n\nPrimero, encuentra una pareja madura o mentor que pueda caminar contigo durante tu compromiso. Debe ser alguien que te conozca lo suficientemente bien como para hacer preguntas difíciles y que te ame lo suficiente como para decirte la verdad. Deben tener acceso a tu relación—no solo la versión pulida que presentas en redes sociales, sino las luchas reales, miedos y desafíos que enfrentas.\n\nSegundo, involucra a tus familias. Sí, son adultos. Sí, tomarán sus propias decisiones. Pero Dios ha puesto familia en tu vida por una razón. Honra a tus padres buscando su opinión y bendición. Incluso si tu situación familiar es complicada, encuentra maneras de incluirlos en tu camino.\n\nTercero, estén conectados a una iglesia local. El matrimonio no es solo entre dos personas—es entre dos personas y su comunidad. Tu iglesia orará por ustedes, los aconsejará, celebrará con ustedes y los apoyará a través de las dificultades inevitables de la vida matrimonial. Si no están conectados a una iglesia, encuentren una ahora. No entren al matrimonio sin una comunidad de fe que los apoye.\n\nCuarto, sean intencionales con su ceremonia de boda. Esto no es meramente una fiesta—es un evento de creación de pacto. Elijan una ceremonia que refleje la seriedad de sus votos. Inviten testigos que los responsabilicen. Hagan sus promesas ante Dios y su comunidad con plena conciencia de lo que están haciendo.\n\nFinalmente, continúen viviendo públicamente después de la boda. No desaparezcan en su nueva vida juntos y descuiden las relaciones que los apoyaron. Manténganse conectados. Manténganse responsables. Que su matrimonio sea un testimonio de la fidelidad de Dios."
    },
    closingCharge: {
      en: "You are about to make the most significant promise of your life. You will stand before God, your family, your friends, and your church, and you will declare your intention to love one person for the rest of your days. This is not a private decision. This is a public covenant.\n\nDo not take this lightly. The witnesses at your wedding are not decorations—they are participants in your covenant. They will watch you make your vows, and they will hold you to them. Choose your witnesses carefully. Invite people who will pray for you, encourage you, and when necessary, challenge you to keep your promises.\n\nRemember that your marriage will be a testimony. The world is watching. Your children will watch. Your friends will watch. Your community will watch. Will your marriage declare the faithfulness of God, or will it echo the brokenness of the world?\n\nLive as witnessed people. Let your relationship be open, accountable, and rooted in community. Do not hide. Do not isolate. Do not believe the lie that your relationship is nobody's business but your own.\n\nMarriage is public because God is public. He does not hide in the shadows. He declares His love openly, and He calls His people to do the same. Go forth as witnesses of covenant love, and let your marriage proclaim the goodness of God to a watching world.",
      es: "Están a punto de hacer la promesa más significativa de sus vidas. Se pararán ante Dios, su familia, sus amigos y su iglesia, y declararán su intención de amar a una persona por el resto de sus días. Esta no es una decisión privada. Este es un pacto público.\n\nNo tomen esto a la ligera. Los testigos en su boda no son decoración—son participantes en su pacto. Los verán hacer sus votos, y los responsabilizarán de cumplirlos. Elijan a sus testigos cuidadosamente. Inviten a personas que orarán por ustedes, los animarán y, cuando sea necesario, los desafiarán a mantener sus promesas.\n\nRecuerden que su matrimonio será un testimonio. El mundo está observando. Sus hijos observarán. Sus amigos observarán. Su comunidad observará. ¿Declarará su matrimonio la fidelidad de Dios, o hará eco de la rotura del mundo?\n\nVivan como personas presenciadas. Que su relación sea abierta, responsable y arraigada en comunidad. No se escondan. No se aíslen. No crean la mentira de que su relación no es asunto de nadie más que de ustedes.\n\nEl matrimonio es público porque Dios es público. Él no se esconde en las sombras. Declara Su amor abiertamente, y llama a Su pueblo a hacer lo mismo. Vayan como testigos del amor de pacto, y que su matrimonio proclame la bondad de Dios a un mundo que observa."
    },
    reflectionQuestions: [
      {
        en: "Who are the witnesses in your relationship journey right now? Are they people who will hold you accountable to your covenant?",
        es: "¿Quiénes son los testigos en su camino de relación ahora mismo? ¿Son personas que los responsabilizarán de su pacto?"
      },
      {
        en: "How does knowing that God Himself is a witness to your vows change your view of commitment?",
        es: "¿Cómo cambia tu visión del compromiso saber que Dios mismo es testigo de tus votos?"
      },
      {
        en: "What testimony does your relationship currently give to others who are watching?",
        es: "¿Qué testimonio da actualmente tu relación a otros que están observando?"
      },
      {
        en: "Are there ways you have tried to keep your relationship private or hidden? Why?",
        es: "¿Hay formas en que has tratado de mantener tu relación privada u oculta? ¿Por qué?"
      },
      {
        en: "How can you more intentionally invite your community into your journey toward marriage?",
        es: "¿Cómo puedes invitar más intencionalmente a tu comunidad en tu camino hacia el matrimonio?"
      }
    ],
    practiceBox: [
      {
        en: "Identify a mature married couple and ask them to mentor you through your engagement.",
        es: "Identifica una pareja casada madura y pídeles que los guíen durante su compromiso."
      },
      {
        en: "Share your relationship story with a trusted mentor or pastor this week.",
        es: "Comparte la historia de tu relación con un mentor o pastor de confianza esta semana."
      },
      {
        en: "Pray together, acknowledging God as the primary witness of your covenant.",
        es: "Oren juntos, reconociendo a Dios como el testigo principal de su pacto."
      },
      {
        en: "Identify one way your relationship can bless and testify to your community this week.",
        es: "Identifica una manera en que tu relación puede bendecir y testificar a tu comunidad esta semana."
      }
    ]
  },
  {
    day: 2,
    title: {
      en: "Accountability Matters",
      es: "La Responsabilidad Importa"
    },
    scriptureAnchor: {
      en: "\"Two are better than one, because they have a good return for their labor: If either of them falls down, one can help the other up. But pity anyone who falls and has no one to help them up.\" — Ecclesiastes 4:9-10\n\n\"Brothers and sisters, if someone is caught in a sin, you who live by the Spirit should restore that person gently.\" — Galatians 6:1",
      es: "\"Mejores son dos que uno; porque tienen mejor paga de su trabajo. Porque si cayeren, el uno levantará a su compañero; pero ¡ay del solo! que cuando cayere, no habrá segundo que lo levante.\" — Eclesiastés 4:9-10\n\n\"Hermanos, si alguno fuere sorprendido en alguna falta, vosotros que sois espirituales, restauradle con espíritu de mansedumbre.\" — Gálatas 6:1"
    },
    exposition: {
      en: "Accountability is not a modern invention designed to invade your privacy. It is a biblical principle woven into the very fabric of covenant community. From the earliest pages of Scripture, God has made it clear that we are not meant to journey alone. We need others to see what we cannot see, to speak truth when we are deceived, and to lift us up when we fall.\n\nThe wisdom of Ecclesiastes declares that two are better than one. This is not merely pragmatic advice about efficiency—it is a profound statement about human nature. We are created for relationship. We are designed to live in community. And when we isolate ourselves, we become vulnerable to deception, sin, and destruction.\n\nAccountability in the context of marriage preparation is essential because the stakes are so high. You are not merely deciding what to eat for dinner or where to go on vacation. You are making a covenant that will shape the rest of your life. You are binding yourself to another person \"until death do us part.\" This is not a decision that should be made in isolation.\n\nWhen couples refuse accountability, they often do so because they fear what others might say. Perhaps they know deep down that something in their relationship is unhealthy. Perhaps they have ignored red flags that a wise mentor would immediately identify. Perhaps they simply want to maintain the illusion that everything is perfect. But accountability is not about judgment—it is about protection.\n\nGalatians 6:1 calls believers to restore one another gently when we fall into sin. This presupposes that we have allowed others close enough to see our struggles. It assumes that we have invited people into our lives who love us enough to speak hard truths. Accountability is an act of humility—an admission that we do not have all the answers and that we need the wisdom and support of others.\n\nIn marriage preparation, accountability serves multiple purposes. It provides an outside perspective on your relationship. It creates space for honest conversation about areas that need growth. It establishes a pattern of openness that will serve you well throughout your marriage. Couples who enter marriage with strong accountability structures are far more likely to navigate difficulties successfully than those who try to go it alone.\n\nThe church has always understood the importance of accountability. This is why premarital counseling exists. This is why wedding ceremonies include witnesses. This is why communities of faith gather around newlywed couples to support and encourage them. Accountability is not an intrusion—it is a gift.",
      es: "La responsabilidad no es una invención moderna diseñada para invadir tu privacidad. Es un principio bíblico tejido en la misma estructura de la comunidad del pacto. Desde las primeras páginas de las Escrituras, Dios ha dejado claro que no estamos destinados a caminar solos. Necesitamos a otros para ver lo que no podemos ver, para hablar verdad cuando estamos engañados, y para levantarnos cuando caemos.\n\nLa sabiduría del Eclesiastés declara que dos son mejor que uno. Esto no es meramente un consejo pragmático sobre eficiencia—es una declaración profunda sobre la naturaleza humana. Somos creados para la relación. Estamos diseñados para vivir en comunidad. Y cuando nos aislamos, nos volvemos vulnerables al engaño, al pecado y a la destrucción.\n\nLa responsabilidad en el contexto de la preparación para el matrimonio es esencial porque lo que está en juego es muy alto. No están meramente decidiendo qué comer para cenar o dónde ir de vacaciones. Están haciendo un pacto que dará forma al resto de sus vidas. Se están uniendo a otra persona \"hasta que la muerte los separe.\" Esta no es una decisión que deba tomarse en aislamiento.\n\nCuando las parejas rechazan la responsabilidad, a menudo lo hacen porque temen lo que otros puedan decir. Quizás saben en el fondo que algo en su relación no es saludable. Quizás han ignorado señales de alerta que un mentor sabio identificaría inmediatamente. Quizás simplemente quieren mantener la ilusión de que todo es perfecto. Pero la responsabilidad no se trata de juicio—se trata de protección.\n\nGálatas 6:1 llama a los creyentes a restaurarse unos a otros con mansedumbre cuando caemos en pecado. Esto presupone que hemos permitido que otros se acerquen lo suficiente para ver nuestras luchas. Asume que hemos invitado a personas a nuestras vidas que nos aman lo suficiente como para hablar verdades difíciles. La responsabilidad es un acto de humildad—una admisión de que no tenemos todas las respuestas y que necesitamos la sabiduría y el apoyo de otros.\n\nEn la preparación para el matrimonio, la responsabilidad sirve múltiples propósitos. Proporciona una perspectiva externa sobre su relación. Crea espacio para conversaciones honestas sobre áreas que necesitan crecer. Establece un patrón de apertura que les servirá bien a lo largo de su matrimonio. Las parejas que entran al matrimonio con estructuras de responsabilidad fuertes tienen muchas más probabilidades de navegar las dificultades exitosamente que aquellos que intentan hacerlo solos.\n\nLa iglesia siempre ha entendido la importancia de la responsabilidad. Por esto existe la consejería prematrimonial. Por esto las ceremonias de boda incluyen testigos. Por esto las comunidades de fe se reúnen alrededor de las parejas recién casadas para apoyarlas y animarlas. La responsabilidad no es una intrusión—es un regalo."
    },
    realityCheck: {
      en: "We live in an age of radical individualism. \"Mind your own business\" has become our cultural creed. We are told that no one has the right to speak into our decisions, that our relationships are our own affair, and that accountability is just a fancy word for control. This is a lie from the pit of hell.\n\nThe rejection of accountability has produced a generation of relationships built on sand. Without outside voices, couples reinforce each other's blind spots. They normalize dysfunction. They mistake intensity for intimacy and passion for love. They walk into marriage with no idea what they are committing to because no one has ever told them the truth.\n\nWorse still, many couples actively hide from accountability. They choose not to tell their parents about their relationship. They skip premarital counseling. They surround themselves with friends who will affirm every decision without question. They create echo chambers where their own voices are the only ones they hear.\n\nThis is a recipe for disaster. Sin thrives in darkness. Deception flourishes in isolation. When no one is watching, we are capable of convincing ourselves of almost anything. We need others to shine light into the corners of our relationships that we would prefer to keep hidden.\n\nThe truth is, if you are afraid of accountability, you should ask yourself why. What are you hiding? What do you fear others will say? What truths are you avoiding? Often, the very things we try to hide are the things that most need to be addressed before marriage.\n\nAccountability is not optional for believers. It is a fundamental aspect of life in the body of Christ. To reject accountability is to reject the wisdom of God and to place yourself above the community He has given you.",
      es: "Vivimos en una era de individualismo radical. \"Ocúpate de tus propios asuntos\" se ha convertido en nuestro credo cultural. Se nos dice que nadie tiene derecho a hablar sobre nuestras decisiones, que nuestras relaciones son asunto nuestro, y que la responsabilidad es solo una palabra elegante para control. Esta es una mentira del infierno.\n\nEl rechazo de la responsabilidad ha producido una generación de relaciones construidas sobre arena. Sin voces externas, las parejas refuerzan los puntos ciegos del otro. Normalizan la disfunción. Confunden intensidad con intimidad y pasión con amor. Caminan hacia el matrimonio sin idea de a qué se están comprometiendo porque nadie les ha dicho la verdad.\n\nPeor aún, muchas parejas se esconden activamente de la responsabilidad. Eligen no contarles a sus padres sobre su relación. Se saltan la consejería prematrimonial. Se rodean de amigos que afirmarán cada decisión sin cuestionar. Crean cámaras de eco donde sus propias voces son las únicas que escuchan.\n\nEsta es una receta para el desastre. El pecado prospera en la oscuridad. El engaño florece en el aislamiento. Cuando nadie está observando, somos capaces de convencernos de casi cualquier cosa. Necesitamos que otros iluminen los rincones de nuestras relaciones que preferiríamos mantener ocultos.\n\nLa verdad es que, si tienes miedo de la responsabilidad, deberías preguntarte por qué. ¿Qué estás escondiendo? ¿Qué temes que otros digan? ¿Qué verdades estás evitando? A menudo, las mismas cosas que tratamos de ocultar son las que más necesitan ser abordadas antes del matrimonio.\n\nLa responsabilidad no es opcional para los creyentes. Es un aspecto fundamental de la vida en el cuerpo de Cristo. Rechazar la responsabilidad es rechazar la sabiduría de Dios y colocarte por encima de la comunidad que Él te ha dado."
    },
    practicalImplications: {
      en: "Building accountability into your relationship requires intentionality. It will not happen automatically. You must choose to open your lives to others and to submit yourselves to their wisdom and correction.\n\nBegin by identifying people who can serve as accountability partners. These should be mature believers who have demonstrated wisdom in their own relationships. Ideally, include a married couple who can speak from experience, a pastor or counselor who can provide spiritual guidance, and trusted friends who know you well.\n\nMeet regularly with these accountability partners. Don't wait until you have a crisis to seek their input. Create space for ongoing conversation about your relationship. Be honest about your struggles, your fears, and your areas of growth. Ask them to tell you the truth, even when it's hard to hear.\n\nBe specific in your accountability. Don't just ask for general prayers. Share specific challenges you are facing. Talk about areas where you are tempted. Discuss conflicts you have had and how you resolved them. The more specific you are, the more helpful your accountability partners can be.\n\nEngage in premarital counseling with a qualified pastor or counselor. This is not a formality to check off a list—it is an essential part of preparing for marriage. Good premarital counseling will help you identify potential areas of conflict, develop healthy communication patterns, and establish a strong foundation for your marriage.\n\nFinally, maintain accountability after the wedding. Many couples disengage from their support systems once they are married, thinking they no longer need outside help. This is a mistake. The challenges of marriage require ongoing support. Stay connected to your accountability partners. Continue to invite others into your relationship. Let your marriage be marked by openness rather than isolation.",
      es: "Construir responsabilidad en tu relación requiere intencionalidad. No sucederá automáticamente. Deben elegir abrir sus vidas a otros y someterse a su sabiduría y corrección.\n\nComiencen identificando personas que puedan servir como compañeros de responsabilidad. Deben ser creyentes maduros que hayan demostrado sabiduría en sus propias relaciones. Idealmente, incluyan una pareja casada que pueda hablar desde la experiencia, un pastor o consejero que pueda proporcionar guía espiritual, y amigos de confianza que los conozcan bien.\n\nReúnanse regularmente con estos compañeros de responsabilidad. No esperen hasta tener una crisis para buscar su opinión. Creen espacio para conversación continua sobre su relación. Sean honestos sobre sus luchas, sus miedos y sus áreas de crecimiento. Pídanles que les digan la verdad, incluso cuando sea difícil de escuchar.\n\nSean específicos en su responsabilidad. No solo pidan oraciones generales. Compartan desafíos específicos que están enfrentando. Hablen sobre áreas donde están tentados. Discutan conflictos que han tenido y cómo los resolvieron. Cuanto más específicos sean, más útiles pueden ser sus compañeros de responsabilidad.\n\nParticipa en consejería prematrimonial con un pastor o consejero calificado. Esto no es una formalidad para marcar de una lista—es una parte esencial de prepararse para el matrimonio. Una buena consejería prematrimonial te ayudará a identificar áreas potenciales de conflicto, desarrollar patrones de comunicación saludables y establecer un fundamento fuerte para tu matrimonio.\n\nFinalmente, mantén la responsabilidad después de la boda. Muchas parejas se desconectan de sus sistemas de apoyo una vez que están casados, pensando que ya no necesitan ayuda externa. Esto es un error. Los desafíos del matrimonio requieren apoyo continuo. Manténganse conectados a sus compañeros de responsabilidad. Continúen invitando a otros a su relación. Que su matrimonio esté marcado por la apertura en lugar del aislamiento."
    },
    closingCharge: {
      en: "You were not meant to walk this journey alone. God has surrounded you with a community of believers who want to see your marriage succeed. They have wisdom you need. They have perspective you lack. They have experience that can guide you through the challenges ahead.\n\nDo not be too proud to ask for help. Do not be too afraid to let others see your struggles. Humility is the pathway to growth, and accountability is one of the primary means God uses to sanctify His people.\n\nIf you truly love each other, you will submit yourselves to accountability. You will invite others to speak into your relationship. You will listen when wise voices offer correction. You will value truth over comfort and growth over ease.\n\nThe alternative is to isolate yourselves and trust your own judgment. History is littered with the wreckage of relationships that followed this path. Do not add your names to the list.\n\nAccountability matters because your marriage matters. Your covenant matters. Your witness matters. So open your lives. Invite others in. Let the light of community shine into every corner of your relationship. This is the path of wisdom. This is the way of blessing. This is how covenant couples are built.",
      es: "No estaban destinados a caminar este viaje solos. Dios los ha rodeado de una comunidad de creyentes que quiere ver su matrimonio tener éxito. Tienen sabiduría que necesitan. Tienen perspectiva que les falta. Tienen experiencia que puede guiarlos a través de los desafíos que vienen.\n\nNo sean demasiado orgullosos para pedir ayuda. No tengan demasiado miedo de dejar que otros vean sus luchas. La humildad es el camino hacia el crecimiento, y la responsabilidad es uno de los medios principales que Dios usa para santificar a Su pueblo.\n\nSi verdaderamente se aman, se someterán a la responsabilidad. Invitarán a otros a hablar sobre su relación. Escucharán cuando voces sabias ofrezcan corrección. Valorarán la verdad sobre la comodidad y el crecimiento sobre la facilidad.\n\nLa alternativa es aislarse y confiar en su propio juicio. La historia está llena de los escombros de relaciones que siguieron este camino. No añadan sus nombres a la lista.\n\nLa responsabilidad importa porque su matrimonio importa. Su pacto importa. Su testimonio importa. Así que abran sus vidas. Inviten a otros. Dejen que la luz de la comunidad brille en cada rincón de su relación. Este es el camino de la sabiduría. Este es el camino de la bendición. Así es como se construyen las parejas del pacto."
    },
    reflectionQuestions: [
      {
        en: "Who currently has permission to speak honestly into your relationship? Are you listening to them?",
        es: "¿Quién tiene actualmente permiso para hablar honestamente sobre tu relación? ¿Los estás escuchando?"
      },
      {
        en: "What areas of your relationship would you prefer to keep hidden from others? Why?",
        es: "¿Qué áreas de tu relación preferirías mantener ocultas de otros? ¿Por qué?"
      },
      {
        en: "How have you responded when others have offered correction or concern about your relationship?",
        es: "¿Cómo has respondido cuando otros han ofrecido corrección o preocupación sobre tu relación?"
      },
      {
        en: "What would change in your relationship if you fully embraced accountability?",
        es: "¿Qué cambiaría en tu relación si abrazaras completamente la responsabilidad?"
      }
    ],
    practiceBox: [
      {
        en: "Schedule a meeting with a mature married couple to discuss your relationship openly.",
        es: "Programa una reunión con una pareja casada madura para discutir tu relación abiertamente."
      },
      {
        en: "Begin premarital counseling with a qualified pastor or counselor this month.",
        es: "Comienza la consejería prematrimonial con un pastor o consejero calificado este mes."
      },
      {
        en: "Write down three areas where you need accountability and share them with a trusted mentor.",
        es: "Escribe tres áreas donde necesitas responsabilidad y compártelas con un mentor de confianza."
      },
      {
        en: "Commit to regular check-ins with an accountability partner throughout your engagement.",
        es: "Comprométete a reuniones regulares con un compañero de responsabilidad durante tu compromiso."
      }
    ]
  },
  {
    day: 3,
    title: {
      en: "God as Ultimate Witness",
      es: "Dios como Testigo Supremo"
    },
    scriptureAnchor: {
      en: "\"The LORD is witness between you and the wife of your youth.\" — Malachi 2:14\n\n\"Nothing in all creation is hidden from God's sight. Everything is uncovered and laid bare before the eyes of him to whom we must give account.\" — Hebrews 4:13",
      es: "\"Jehová ha atestiguado entre ti y la mujer de tu juventud.\" — Malaquías 2:14\n\n\"Y no hay cosa creada que no sea manifiesta en su presencia; antes bien todas las cosas están desnudas y abiertas a los ojos de aquel a quien tenemos que dar cuenta.\" — Hebreos 4:13"
    },
    exposition: {
      en: "Every wedding ceremony, whether grand or simple, has one witness who is always present: God Himself. Long before your family gathers, before your friends take their seats, before the officiant speaks the first word, the Almighty stands ready to witness your vows. And unlike human witnesses who may forget or pass away, God's witness is eternal.\n\nThis truth should stir both comfort and holy fear within every couple preparing for marriage. Comfort, because you are not entering into covenant alone—the Creator of the universe is present to bless and uphold your union. Fear, because the One who witnesses your vows sees all things, knows all things, and will hold you accountable for every promise you make.\n\nMalachi speaks directly to this reality. In addressing the men of Israel who had dealt treacherously with their wives, the prophet declares: \"The LORD is witness between you and the wife of your youth.\" God had seen their covenant. God had heard their vows. And God would not overlook their betrayal. The marriage covenant is not merely a horizontal agreement between two humans—it is a vertical commitment before the living God.\n\nHebrews 4:13 expands this truth to encompass all of life: \"Nothing in all creation is hidden from God's sight.\" Every word spoken in your relationship, every action taken behind closed doors, every thought harbored in your heart—all of it is \"uncovered and laid bare\" before God. You cannot hide from Him. You cannot deceive Him. You cannot make promises in His presence and expect to break them without consequence.\n\nThis is why marriage vows matter. When you say \"I do,\" you are not simply expressing a current intention. You are making a solemn promise before the eternal God. He hears your words. He weighs your heart. He will remember your covenant long after the wedding flowers have wilted and the photographs have faded.\n\nThe presence of God as witness transforms marriage from a mere social arrangement into a sacred covenant. It elevates your union beyond cultural norms and personal preferences. It anchors your commitment in something far more substantial than fleeting emotions or temporary circumstances. When God witnesses your vows, your marriage becomes part of His eternal purposes.\n\nThis understanding should shape how you prepare for marriage. If God is watching, then your engagement should be marked by integrity. If God is listening, then your words to each other should be true. If God will hold you accountable, then your promises should be made with trembling seriousness.",
      es: "Cada ceremonia de boda, ya sea grande o sencilla, tiene un testigo que siempre está presente: Dios mismo. Mucho antes de que tu familia se reúna, antes de que tus amigos tomen sus asientos, antes de que el oficiante hable la primera palabra, el Todopoderoso está listo para presenciar tus votos. Y a diferencia de los testigos humanos que pueden olvidar o fallecer, el testimonio de Dios es eterno.\n\nEsta verdad debería despertar tanto consuelo como santo temor en cada pareja que se prepara para el matrimonio. Consuelo, porque no están entrando en el pacto solos—el Creador del universo está presente para bendecir y sostener su unión. Temor, porque Aquel que presencia sus votos ve todas las cosas, sabe todas las cosas, y los hará responsables de cada promesa que hagan.\n\nMalaquías habla directamente de esta realidad. Al dirigirse a los hombres de Israel que habían tratado traidoramente con sus esposas, el profeta declara: \"Jehová ha atestiguado entre ti y la mujer de tu juventud.\" Dios había visto su pacto. Dios había oído sus votos. Y Dios no pasaría por alto su traición. El pacto matrimonial no es meramente un acuerdo horizontal entre dos humanos—es un compromiso vertical ante el Dios viviente.\n\nHebreos 4:13 expande esta verdad para abarcar toda la vida: \"No hay cosa creada que no sea manifiesta en su presencia.\" Cada palabra hablada en tu relación, cada acción tomada a puertas cerradas, cada pensamiento albergado en tu corazón—todo está \"desnudo y abierto\" ante Dios. No puedes esconderte de Él. No puedes engañarlo. No puedes hacer promesas en Su presencia y esperar romperlas sin consecuencias.\n\nEs por eso que los votos matrimoniales importan. Cuando dices \"Acepto,\" no estás simplemente expresando una intención actual. Estás haciendo una promesa solemne ante el Dios eterno. Él escucha tus palabras. Él pesa tu corazón. Él recordará tu pacto mucho después de que las flores de la boda se hayan marchitado y las fotografías se hayan desvanecido.\n\nLa presencia de Dios como testigo transforma el matrimonio de un mero arreglo social a un pacto sagrado. Eleva tu unión más allá de las normas culturales y preferencias personales. Ancla tu compromiso en algo mucho más sustancial que emociones pasajeras o circunstancias temporales. Cuando Dios presencia tus votos, tu matrimonio se convierte en parte de Sus propósitos eternos.\n\nEste entendimiento debe dar forma a cómo te preparas para el matrimonio. Si Dios está observando, entonces tu compromiso debe estar marcado por integridad. Si Dios está escuchando, entonces tus palabras el uno al otro deben ser verdaderas. Si Dios te hará responsable, entonces tus promesas deben hacerse con seria solemnidad."
    },
    realityCheck: {
      en: "We live in a world that has largely forgotten God. Even among those who profess faith, there is a practical atheism that governs daily life. We make decisions as though God is not watching. We speak as though God is not listening. We act as though we will never give an account for our choices.\n\nThis forgetfulness has infected our understanding of marriage. Many couples recite vows that mention God but live as though He is irrelevant to their relationship. They invoke His name at the wedding but ignore His presence in the home. They promise \"before God and these witnesses\" but conduct their marriage as though no one is watching.\n\nThe consequences are devastating. When we forget that God is witness to our covenant, we lower our standards. We cut corners. We make excuses for behavior that violates our vows. We tell ourselves that what happens in private doesn't matter. We convince ourselves that our spouse will never know, so it must be acceptable.\n\nBut God knows. God always knows. And His witness is not passive—it is active. He does not merely observe; He judges. He does not simply watch; He weighs. Every broken promise, every act of betrayal, every moment of unfaithfulness is recorded in heaven.\n\nThis is not meant to paralyze you with fear but to awaken you to reality. Your marriage is not a private arrangement between you and your spouse. It is a covenant made before the God of the universe. He is invested in your success. He has promised to be with you. But He also requires faithfulness.\n\nThe fear of the Lord is the beginning of wisdom. If you truly understand that God witnesses your vows, you will approach marriage with appropriate seriousness. You will guard your words, your actions, and your heart. You will live as though you are always being watched—because you are.",
      es: "Vivimos en un mundo que ha olvidado en gran medida a Dios. Incluso entre aquellos que profesan fe, hay un ateísmo práctico que gobierna la vida diaria. Tomamos decisiones como si Dios no estuviera observando. Hablamos como si Dios no estuviera escuchando. Actuamos como si nunca tuviéramos que dar cuenta de nuestras decisiones.\n\nEste olvido ha infectado nuestro entendimiento del matrimonio. Muchas parejas recitan votos que mencionan a Dios pero viven como si Él fuera irrelevante para su relación. Invocan Su nombre en la boda pero ignoran Su presencia en el hogar. Prometen \"ante Dios y estos testigos\" pero conducen su matrimonio como si nadie estuviera observando.\n\nLas consecuencias son devastadoras. Cuando olvidamos que Dios es testigo de nuestro pacto, bajamos nuestros estándares. Tomamos atajos. Ponemos excusas para comportamientos que violan nuestros votos. Nos decimos que lo que pasa en privado no importa. Nos convencemos de que nuestro cónyuge nunca lo sabrá, así que debe ser aceptable.\n\nPero Dios sabe. Dios siempre sabe. Y Su testimonio no es pasivo—es activo. Él no meramente observa; Él juzga. Él no simplemente mira; Él pesa. Cada promesa rota, cada acto de traición, cada momento de infidelidad está registrado en el cielo.\n\nEsto no está destinado a paralizarte con miedo sino a despertarte a la realidad. Tu matrimonio no es un arreglo privado entre tú y tu cónyuge. Es un pacto hecho ante el Dios del universo. Él está invertido en tu éxito. Ha prometido estar contigo. Pero también requiere fidelidad.\n\nEl temor del Señor es el principio de la sabiduría. Si verdaderamente entiendes que Dios presencia tus votos, te acercarás al matrimonio con la seriedad apropiada. Guardarás tus palabras, tus acciones y tu corazón. Vivirás como si siempre estuvieras siendo observado—porque lo estás."
    },
    practicalImplications: {
      en: "Living with an awareness of God's witness requires daily intentionality. It is not enough to acknowledge His presence at the wedding and then forget Him in the routine of married life. You must cultivate a continuous consciousness of His watchful eye.\n\nBegin each day by inviting God into your relationship. Pray together, acknowledging Him as the witness of your covenant. Ask Him to help you honor your vows in the small moments as well as the significant ones. Thank Him for His presence and ask for His guidance.\n\nWhen you are tempted to speak harshly to each other, remember that God is listening. When you are tempted to act in ways that violate your commitment, remember that God is watching. When you are tempted to harbor resentment or unforgiveness in your heart, remember that God sees.\n\nEstablish rhythms of accountability that remind you of God's witness. Regular prayer together keeps His presence at the center of your relationship. Reading Scripture together reminds you of His standards and His promises. Worship together connects your marriage to the broader community of faith.\n\nMake decisions as a couple with God's perspective in mind. Before making significant choices, ask yourselves: \"Would we be comfortable if God could see this decision?\" The reality is, He can. So make choices that honor Him.\n\nWhen you fail—and you will fail—confess your sins to God and to each other. Do not try to hide your failures, as though God didn't already see them. Instead, bring them into the light. Repent. Receive forgiveness. And recommit yourself to living faithfully before the God who witnesses your covenant.\n\nFinally, find comfort in God's witness. He is not merely watching to catch you in failure. He is watching to support you, guide you, and bless you. He wants your marriage to succeed. He has given you His Spirit to empower you and His Word to direct you. His witness is a gift, not a burden.",
      es: "Vivir con conciencia del testimonio de Dios requiere intencionalidad diaria. No es suficiente reconocer Su presencia en la boda y luego olvidarlo en la rutina de la vida matrimonial. Debes cultivar una conciencia continua de Su mirada vigilante.\n\nComienza cada día invitando a Dios a tu relación. Oren juntos, reconociéndolo como el testigo de su pacto. Pídanle que les ayude a honrar sus votos en los momentos pequeños así como en los significativos. Agrádezcanle por Su presencia y pidan Su guía.\n\nCuando estés tentado a hablar duramente el uno al otro, recuerda que Dios está escuchando. Cuando estés tentado a actuar de maneras que violan tu compromiso, recuerda que Dios está observando. Cuando estés tentado a albergar resentimiento o falta de perdón en tu corazón, recuerda que Dios ve.\n\nEstablezcan ritmos de responsabilidad que les recuerden el testimonio de Dios. La oración regular juntos mantiene Su presencia en el centro de su relación. Leer las Escrituras juntos les recuerda Sus estándares y Sus promesas. Adorar juntos conecta su matrimonio con la comunidad más amplia de fe.\n\nTomen decisiones como pareja con la perspectiva de Dios en mente. Antes de tomar decisiones significativas, pregúntense: \"¿Estaríamos cómodos si Dios pudiera ver esta decisión?\" La realidad es que Él puede. Así que tomen decisiones que lo honren.\n\nCuando fallen—y fallarán—confiesen sus pecados a Dios y el uno al otro. No traten de ocultar sus fracasos, como si Dios no los hubiera visto ya. En cambio, tráiganlos a la luz. Arrepiéntanse. Reciban perdón. Y vuelvan a comprometerse a vivir fielmente ante el Dios que presencia su pacto.\n\nFinalmente, encuentren consuelo en el testimonio de Dios. Él no está meramente observando para atraparlos en el fracaso. Él está observando para apoyarlos, guiarlos y bendecirlos. Él quiere que su matrimonio tenga éxito. Les ha dado Su Espíritu para empoderarlos y Su Palabra para dirigirlos. Su testimonio es un regalo, no una carga."
    },
    closingCharge: {
      en: "You are about to make promises before the God of heaven and earth. This is not a light thing. The One who spoke the universe into existence will hear your vows. The One who knows the number of hairs on your head will weigh your words. The One who sees into the depths of your heart will witness your covenant.\n\nLet this reality transform how you approach marriage. Do not make promises you do not intend to keep. Do not speak vows you are not prepared to fulfill. Do not enter into covenant casually, as though God were not watching.\n\nBut also let this reality bring you profound comfort. You are not alone. The God who witnesses your vows is also the God who sustains your marriage. He is for you, not against you. He desires your flourishing. He will provide grace for every challenge you face.\n\nLive your marriage before the face of God. Make decisions in His presence. Speak to each other as though He is listening. Act as though He is watching. Because He is.\n\nWhen you stand at the altar and declare your vows, look beyond your spouse, beyond your family, beyond your friends—and see the God who stands ready to witness your covenant. Make your promises to Him as much as to each other. And then go forth to build a marriage that honors the One who brought you together.",
      es: "Están a punto de hacer promesas ante el Dios del cielo y la tierra. Esto no es cosa ligera. Aquel que habló el universo a la existencia escuchará sus votos. Aquel que conoce el número de cabellos en tu cabeza pesará tus palabras. Aquel que ve en las profundidades de tu corazón presenciará tu pacto.\n\nQue esta realidad transforme cómo te acercas al matrimonio. No hagas promesas que no tienes intención de cumplir. No hables votos que no estás preparado para cumplir. No entres en el pacto casualmente, como si Dios no estuviera observando.\n\nPero también deja que esta realidad te traiga profundo consuelo. No estás solo. El Dios que presencia tus votos es también el Dios que sostiene tu matrimonio. Él está a tu favor, no en tu contra. Él desea tu florecimiento. Él proveerá gracia para cada desafío que enfrentes.\n\nVive tu matrimonio ante la faz de Dios. Toma decisiones en Su presencia. Háblense el uno al otro como si Él estuviera escuchando. Actúen como si Él estuviera observando. Porque lo está.\n\nCuando estés en el altar y declares tus votos, mira más allá de tu cónyuge, más allá de tu familia, más allá de tus amigos—y ve al Dios que está listo para presenciar tu pacto. Haz tus promesas a Él tanto como el uno al otro. Y luego ve a construir un matrimonio que honre a Aquel que los unió."
    },
    reflectionQuestions: [
      {
        en: "How does knowing that God witnesses your covenant change how you view your marriage vows?",
        es: "¿Cómo cambia tu visión de los votos matrimoniales saber que Dios presencia tu pacto?"
      },
      {
        en: "In what areas of your relationship have you been living as though God is not watching?",
        es: "¿En qué áreas de tu relación has estado viviendo como si Dios no estuviera observando?"
      },
      {
        en: "How can you cultivate a greater awareness of God's presence in your daily interactions with each other?",
        es: "¿Cómo puedes cultivar una mayor conciencia de la presencia de Dios en tus interacciones diarias con el otro?"
      },
      {
        en: "Does the thought of God as witness bring you more comfort or more fear? Why?",
        es: "¿El pensamiento de Dios como testigo te trae más consuelo o más temor? ¿Por qué?"
      }
    ],
    practiceBox: [
      {
        en: "Begin and end each day this week with prayer together, acknowledging God as the witness of your covenant.",
        es: "Comiencen y terminen cada día esta semana con oración juntos, reconociendo a Dios como el testigo de su pacto."
      },
      {
        en: "Read Malachi 2:13-16 together and discuss what it means for God to witness marriage.",
        es: "Lean Malaquías 2:13-16 juntos y discutan qué significa que Dios presencie el matrimonio."
      },
      {
        en: "Confess to each other any areas where you have acted as though God was not watching.",
        es: "Confiésense el uno al otro cualquier área donde hayan actuado como si Dios no estuviera observando."
      },
      {
        en: "Write a letter to God expressing your commitment to honor Him in your marriage.",
        es: "Escribe una carta a Dios expresando tu compromiso de honrarlo en tu matrimonio."
      }
    ]
  }
];

// Generate remaining devotionals (days 4-22) with the full structure
const remainingTitles = [
  { en: "Covenant, Not Contract", es: "Pacto, No Contrato" },
  { en: "Your Relationship Testifies", es: "Tu Relación Testifica" },
  { en: "Sacredness of Marriage", es: "La Sacralidad del Matrimonio" },
  { en: "Companionship Is Core", es: "El Compañerismo Es Central" },
  { en: "Growth Together", es: "Crecimiento Juntos" },
  { en: "Joy Shared", es: "Alegría Compartida" },
  { en: "Mutual Support", es: "Apoyo Mutuo" },
  { en: "Facing Trials as One", es: "Enfrentando Pruebas como Uno" },
  { en: "Blessing Invites God In", es: "La Bendición Invita a Dios" },
  { en: "Prayer Anchors Union", es: "La Oración Ancla la Unión" },
  { en: "Gratitude Is Essential", es: "La Gratitud Es Esencial" },
  { en: "Protection Promised", es: "Protección Prometida" },
  { en: "Grace Needed Daily", es: "Gracia Necesaria Diariamente" },
  { en: "To Have and To Hold", es: "Para Tenerte y Sostenerte" },
  { en: "For Better, For Worse", es: "En lo Bueno y en lo Malo" },
  { en: "For Richer, For Poorer", es: "En la Riqueza y en la Pobreza" },
  { en: "In Sickness and In Health", es: "En la Enfermedad y en la Salud" },
  { en: "To Love and To Cherish", es: "Para Amar y Apreciar" },
  { en: "Until Death Do Us Part", es: "Hasta Que la Muerte Nos Separe" }
];

// Add remaining devotionals with full content
for (let i = 0; i < remainingTitles.length; i++) {
  const dayNum = i + 4;
  const title = remainingTitles[i];
  
  sayingIDoEntries.push({
    day: dayNum,
    title: title,
    scriptureAnchor: generateScriptureForDay(dayNum, title),
    exposition: generateExpositionForDay(dayNum, title),
    realityCheck: generateRealityCheckForDay(dayNum, title),
    practicalImplications: generatePracticalImplicationsForDay(dayNum, title),
    closingCharge: generateClosingChargeForDay(dayNum, title),
    reflectionQuestions: generateReflectionQuestionsForDay(dayNum, title),
    practiceBox: generatePracticeBoxForDay(dayNum, title)
  });
}

function generateScriptureForDay(day: number, title: BilingualText): BilingualText {
  const scriptures: Record<number, BilingualText> = {
    4: {
      en: "\"This is now bone of my bones and flesh of my flesh.\" — Genesis 2:23\n\n\"I will make a covenant of peace with them; it will be an everlasting covenant.\" — Ezekiel 37:26",
      es: "\"Esto es ahora hueso de mis huesos y carne de mi carne.\" — Génesis 2:23\n\n\"Y haré con ellos pacto de paz, pacto perpetuo será con ellos.\" — Ezequiel 37:26"
    },
    5: {
      en: "\"By this everyone will know that you are my disciples, if you love one another.\" — John 13:35\n\n\"Husbands, love your wives, just as Christ loved the church.\" — Ephesians 5:25",
      es: "\"En esto conocerán todos que sois mis discípulos, si tuviereis amor los unos con los otros.\" — Juan 13:35\n\n\"Maridos, amad a vuestras mujeres, así como Cristo amó a la iglesia.\" — Efesios 5:25"
    },
    6: {
      en: "\"Marriage should be honored by all, and the marriage bed kept pure.\" — Hebrews 13:4\n\n\"So they are no longer two, but one flesh.\" — Matthew 19:6",
      es: "\"Honroso sea en todos el matrimonio, y el lecho sin mancilla.\" — Hebreos 13:4\n\n\"Así que no son ya más dos, sino una sola carne.\" — Mateo 19:6"
    },
    7: {
      en: "\"It is not good that the man should be alone; I will make him a helper fit for him.\" — Genesis 2:18\n\n\"A friend loves at all times, and a brother is born for adversity.\" — Proverbs 17:17",
      es: "\"No es bueno que el hombre esté solo; le haré ayuda idónea para él.\" — Génesis 2:18\n\n\"En todo tiempo ama el amigo, y es como un hermano en tiempo de angustia.\" — Proverbios 17:17"
    },
    8: {
      en: "\"Iron sharpens iron, and one man sharpens another.\" — Proverbs 27:17\n\n\"Being confident of this, that he who began a good work in you will carry it on to completion.\" — Philippians 1:6",
      es: "\"Hierro con hierro se aguza; y así el hombre aguza el rostro de su amigo.\" — Proverbios 27:17\n\n\"Estando persuadido de esto, que el que comenzó en vosotros la buena obra, la perfeccionará.\" — Filipenses 1:6"
    },
    9: {
      en: "\"A joyful heart is good medicine.\" — Proverbs 17:22\n\n\"Rejoice in the Lord always; again I will say, rejoice!\" — Philippians 4:4",
      es: "\"El corazón alegre constituye buen remedio.\" — Proverbios 17:22\n\n\"Regocijaos en el Señor siempre. Otra vez digo: ¡Regocijaos!\" — Filipenses 4:4"
    },
    10: {
      en: "\"Carry each other's burdens, and in this way you will fulfill the law of Christ.\" — Galatians 6:2\n\n\"Be completely humble and gentle; be patient, bearing with one another in love.\" — Ephesians 4:2",
      es: "\"Sobrellevad los unos las cargas de los otros, y cumplid así la ley de Cristo.\" — Gálatas 6:2\n\n\"Con toda humildad y mansedumbre, soportándoos con paciencia los unos a los otros en amor.\" — Efesios 4:2"
    },
    11: {
      en: "\"Count it all joy, my brothers, when you meet trials of various kinds.\" — James 1:2\n\n\"Two are better than one... if either of them falls down, one can help the other up.\" — Ecclesiastes 4:9-10",
      es: "\"Hermanos míos, tened por sumo gozo cuando os halléis en diversas pruebas.\" — Santiago 1:2\n\n\"Mejores son dos que uno... porque si cayeren, el uno levantará a su compañero.\" — Eclesiastés 4:9-10"
    },
    12: {
      en: "\"The LORD bless you and keep you; the LORD make his face shine on you.\" — Numbers 6:24-25\n\n\"Unless the LORD builds the house, the builders labor in vain.\" — Psalm 127:1",
      es: "\"Jehová te bendiga, y te guarde; Jehová haga resplandecer su rostro sobre ti.\" — Números 6:24-25\n\n\"Si Jehová no edificare la casa, en vano trabajan los que la edifican.\" — Salmo 127:1"
    },
    13: {
      en: "\"The prayer of a righteous person is powerful and effective.\" — James 5:16\n\n\"Where two or three gather in my name, there am I with them.\" — Matthew 18:20",
      es: "\"La oración eficaz del justo puede mucho.\" — Santiago 5:16\n\n\"Porque donde están dos o tres congregados en mi nombre, allí estoy yo en medio de ellos.\" — Mateo 18:20"
    },
    14: {
      en: "\"Give thanks in all circumstances; for this is God's will for you.\" — 1 Thessalonians 5:18\n\n\"Enter his gates with thanksgiving and his courts with praise.\" — Psalm 100:4",
      es: "\"Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros.\" — 1 Tesalonicenses 5:18\n\n\"Entrad por sus puertas con acción de gracias, por sus atrios con alabanza.\" — Salmo 100:4"
    },
    15: {
      en: "\"He who dwells in the shelter of the Most High will rest in the shadow of the Almighty.\" — Psalm 91:1\n\n\"The name of the LORD is a fortified tower; the righteous run to it and are safe.\" — Proverbs 18:10",
      es: "\"El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.\" — Salmo 91:1\n\n\"Torre fuerte es el nombre de Jehová; a él correrá el justo, y será levantado.\" — Proverbios 18:10"
    },
    16: {
      en: "\"But by the grace of God I am what I am.\" — 1 Corinthians 15:10\n\n\"My grace is sufficient for you, for my power is made perfect in weakness.\" — 2 Corinthians 12:9",
      es: "\"Pero por la gracia de Dios soy lo que soy.\" — 1 Corintios 15:10\n\n\"Bástate mi gracia; porque mi poder se perfecciona en la debilidad.\" — 2 Corintios 12:9"
    },
    17: {
      en: "\"Therefore a man shall leave his father and his mother and hold fast to his wife.\" — Genesis 2:24\n\n\"Let love be genuine. Hold fast to what is good.\" — Romans 12:9",
      es: "\"Por tanto, dejará el hombre a su padre y a su madre, y se unirá a su mujer.\" — Génesis 2:24\n\n\"El amor sea sin fingimiento. Aborreced lo malo, seguid lo bueno.\" — Romanos 12:9"
    },
    18: {
      en: "\"Love bears all things, believes all things, hopes all things, endures all things.\" — 1 Corinthians 13:7\n\n\"Though the mountains be shaken... yet my unfailing love for you will not be shaken.\" — Isaiah 54:10",
      es: "\"Todo lo sufre, todo lo cree, todo lo espera, todo lo soporta.\" — 1 Corintios 13:7\n\n\"Aunque los montes se muevan... nunca se apartará de ti mi misericordia.\" — Isaías 54:10"
    },
    19: {
      en: "\"Better a little with the fear of the LORD than great wealth with turmoil.\" — Proverbs 15:16\n\n\"Keep your lives free from the love of money and be content with what you have.\" — Hebrews 13:5",
      es: "\"Mejor es lo poco con el temor de Jehová, que el gran tesoro donde hay turbación.\" — Proverbios 15:16\n\n\"Sean vuestras costumbres sin avaricia, contentos con lo que tenéis ahora.\" — Hebreos 13:5"
    },
    20: {
      en: "\"Is anyone among you sick? Let them call the elders of the church to pray over them.\" — James 5:14\n\n\"Heal me, LORD, and I will be healed; save me and I will be saved.\" — Jeremiah 17:14",
      es: "\"¿Está alguno enfermo entre vosotros? Llame a los ancianos de la iglesia, y oren por él.\" — Santiago 5:14\n\n\"Sáname, oh Jehová, y seré sano; sálvame, y seré salvo.\" — Jeremías 17:14"
    },
    21: {
      en: "\"Be devoted to one another in love. Honor one another above yourselves.\" — Romans 12:10\n\n\"Above all, love each other deeply, because love covers over a multitude of sins.\" — 1 Peter 4:8",
      es: "\"Amaos los unos a los otros con amor fraternal; en cuanto a honra, prefiriéndoos los unos a los otros.\" — Romanos 12:10\n\n\"Y ante todo, tened entre vosotros ferviente amor; porque el amor cubrirá multitud de pecados.\" — 1 Pedro 4:8"
    },
    22: {
      en: "\"Love is as strong as death... Many waters cannot quench love; rivers cannot sweep it away.\" — Song of Solomon 8:6-7\n\n\"For I am convinced that neither death nor life... will be able to separate us from the love of God.\" — Romans 8:38-39",
      es: "\"Fuerte es como la muerte el amor... Las muchas aguas no podrán apagar el amor, ni lo ahogarán los ríos.\" — Cantares 8:6-7\n\n\"Por lo cual estoy seguro de que ni la muerte, ni la vida... nos podrá separar del amor de Dios.\" — Romanos 8:38-39"
    }
  };
  return scriptures[day] || { en: "", es: "" };
}

function generateExpositionForDay(day: number, title: BilingualText): BilingualText {
  const expositions: Record<number, BilingualText> = {
    4: {
      en: "The modern world reduces marriage to a contract—a legal arrangement that can be renegotiated or terminated when circumstances change. But Scripture presents marriage as something far more profound: a covenant. This distinction is not merely semantic; it is the difference between a disposable agreement and an unbreakable bond.\n\nA contract is based on mutual benefit. Each party enters with the expectation of receiving something in return for what they give. If one party fails to deliver, the contract can be voided. The relationship is fundamentally transactional—I will love you as long as you meet my needs. I will stay as long as you make me happy.\n\nA covenant operates on entirely different principles. In biblical covenants, God initiates the relationship, defines the terms, and binds Himself to His promises regardless of the other party's performance. The covenant is not conditional on the recipient's worthiness but on the covenant-maker's faithfulness. This is the model for marriage.\n\nWhen God brought Eve to Adam, He established a covenant relationship. \"This is now bone of my bones and flesh of my flesh,\" Adam declared. This was not a business arrangement but a union of life itself. The two became one—not merely in emotion or intention, but in covenant identity.\n\nA covenant marriage says: I am committed to you regardless of what you do. My faithfulness is not contingent on your performance. I will love you when you are lovely and when you are not. I will stay when it is easy and when it is hard. I have bound myself to you, and I will not break my word.\n\nThis is radical in a world that views relationships as disposable. It contradicts everything our culture teaches about protecting yourself and keeping your options open. But it is precisely this radical commitment that creates the safety and security needed for true intimacy to flourish.\n\nWhen you know your spouse will never leave—not because they are trapped, but because they have covenanted to stay—you can be vulnerable. You can share your deepest fears and greatest hopes. You can fail and know you will still be loved. This is the gift of covenant.",
      es: "El mundo moderno reduce el matrimonio a un contrato—un arreglo legal que puede renegociarse o terminarse cuando las circunstancias cambian. Pero las Escrituras presentan el matrimonio como algo mucho más profundo: un pacto. Esta distinción no es meramente semántica; es la diferencia entre un acuerdo desechable y un vínculo inquebrantable.\n\nUn contrato se basa en el beneficio mutuo. Cada parte entra con la expectativa de recibir algo a cambio de lo que da. Si una parte no cumple, el contrato puede anularse. La relación es fundamentalmente transaccional—te amaré mientras satisfagas mis necesidades. Me quedaré mientras me hagas feliz.\n\nUn pacto opera con principios completamente diferentes. En los pactos bíblicos, Dios inicia la relación, define los términos y se compromete a Sus promesas independientemente del desempeño de la otra parte. El pacto no está condicionado a la dignidad del receptor sino a la fidelidad del que hace el pacto. Este es el modelo para el matrimonio.\n\nCuando Dios trajo a Eva a Adán, estableció una relación de pacto. \"Esto es ahora hueso de mis huesos y carne de mi carne,\" declaró Adán. Esto no era un arreglo de negocios sino una unión de la vida misma. Los dos se convirtieron en uno—no meramente en emoción o intención, sino en identidad de pacto.\n\nUn matrimonio de pacto dice: Estoy comprometido contigo independientemente de lo que hagas. Mi fidelidad no está condicionada a tu desempeño. Te amaré cuando seas amable y cuando no lo seas. Me quedaré cuando sea fácil y cuando sea difícil. Me he unido a ti, y no romperé mi palabra.\n\nEsto es radical en un mundo que ve las relaciones como desechables. Contradice todo lo que nuestra cultura enseña sobre protegerte y mantener tus opciones abiertas. Pero es precisamente este compromiso radical lo que crea la seguridad necesaria para que florezca la verdadera intimidad.\n\nCuando sabes que tu cónyuge nunca se irá—no porque esté atrapado, sino porque ha pactado quedarse—puedes ser vulnerable. Puedes compartir tus miedos más profundos y tus mayores esperanzas. Puedes fallar y saber que aún serás amado. Este es el regalo del pacto."
    },
    5: {
      en: "Your relationship is not invisible. Every couple, whether they realize it or not, is constantly communicating something to the world around them. The way you speak to each other, the way you resolve conflict, the way you show affection—all of it sends a message. Your relationship testifies.\n\nJesus declared that the world would know His disciples by their love for one another. This principle applies powerfully to marriage. A Christian marriage should be distinguishable from the marriages of those who do not know Christ. It should demonstrate something different—something better—something that points people to the love of God.\n\nWhen Paul instructs husbands to love their wives as Christ loved the church, he is not merely giving practical marriage advice. He is revealing that marriage is meant to be an illustration of the gospel. Your union should tell the story of Christ's sacrificial love for His bride. It should demonstrate covenant faithfulness in a world of broken promises.\n\nThis is an enormous responsibility and an extraordinary privilege. Your marriage can be a light in the darkness. It can show people what love looks like when it is rooted in Christ. It can give hope to those who have never seen a healthy relationship. It can be a powerful witness to the transforming power of the gospel.\n\nBut the testimony goes both ways. If your marriage is marked by selfishness, conflict, and unfaithfulness, it also sends a message. It tells the watching world that Christianity makes no real difference. It suggests that the love of Christ is insufficient to transform relationships. It becomes a stumbling block rather than a stepping stone to faith.\n\nEvery argument overheard by neighbors, every cold shoulder witnessed by friends, every harsh word spoken in public testifies to something. Your children are watching. Your coworkers are watching. Your community is watching. What is your relationship declaring about the God you claim to serve?",
      es: "Tu relación no es invisible. Cada pareja, lo reconozcan o no, está constantemente comunicando algo al mundo que los rodea. La forma en que se hablan, la forma en que resuelven conflictos, la forma en que muestran afecto—todo envía un mensaje. Tu relación testifica.\n\nJesús declaró que el mundo conocería a Sus discípulos por su amor los unos por los otros. Este principio se aplica poderosamente al matrimonio. Un matrimonio cristiano debería distinguirse de los matrimonios de aquellos que no conocen a Cristo. Debería demostrar algo diferente—algo mejor—algo que señale a las personas hacia el amor de Dios.\n\nCuando Pablo instruye a los esposos a amar a sus esposas como Cristo amó a la iglesia, no está meramente dando consejos prácticos para el matrimonio. Está revelando que el matrimonio está destinado a ser una ilustración del evangelio. Tu unión debería contar la historia del amor sacrificial de Cristo por Su novia. Debería demostrar fidelidad de pacto en un mundo de promesas rotas.\n\nEsta es una responsabilidad enorme y un privilegio extraordinario. Tu matrimonio puede ser una luz en la oscuridad. Puede mostrar a las personas cómo se ve el amor cuando está arraigado en Cristo. Puede dar esperanza a aquellos que nunca han visto una relación saludable. Puede ser un testimonio poderoso del poder transformador del evangelio.\n\nPero el testimonio va en ambas direcciones. Si tu matrimonio está marcado por el egoísmo, el conflicto y la infidelidad, también envía un mensaje. Le dice al mundo observador que el cristianismo no hace ninguna diferencia real. Sugiere que el amor de Cristo es insuficiente para transformar las relaciones. Se convierte en un tropiezo en lugar de un escalón hacia la fe.\n\nCada discusión escuchada por los vecinos, cada hombro frío presenciado por amigos, cada palabra dura dicha en público testifica algo. Tus hijos están observando. Tus compañeros de trabajo están observando. Tu comunidad está observando. ¿Qué está declarando tu relación sobre el Dios al que dices servir?"
    }
  };
  
  // For days without specific content, generate based on title
  if (!expositions[day]) {
    return {
      en: `The principle of "${title.en}" strikes at the heart of what marriage truly means. Scripture does not present marriage as a convenience or a social arrangement, but as a profound spiritual reality that reflects God's own nature and His relationship with His people.\n\nWhen couples commit to marriage, they are entering into something far greater than themselves. They are participating in a divine institution established at creation and honored throughout redemptive history. This truth demands our attention, our respect, and our wholehearted commitment.\n\nThe depth of this principle can only be grasped when we understand marriage from God's perspective. He is not a distant observer of our unions but an active participant who designed marriage for our flourishing and His glory. Every aspect of the marriage covenant points beyond itself to eternal realities.\n\nAs you prepare for marriage, meditate deeply on what "${title.en}" means for your relationship. How will this truth shape the decisions you make? How will it guide you through difficulties? How will it transform your understanding of commitment?\n\nThe world offers many counterfeits of marriage—arrangements based on convenience, passion, or mutual benefit. But God's design is something altogether different. It is covenant love that reflects His own faithful heart. It is sacrificial commitment that mirrors Christ's love for the church. It is enduring faithfulness that testifies to eternal promises.\n\nDo not settle for anything less than God's design. Do not let the world's low expectations become your standard. Rise to the calling that Scripture places before you, and build a marriage that honors the One who brought you together.`,
      es: `El principio de "${title.es}" llega al corazón de lo que realmente significa el matrimonio. Las Escrituras no presentan el matrimonio como una conveniencia o un arreglo social, sino como una realidad espiritual profunda que refleja la propia naturaleza de Dios y Su relación con Su pueblo.\n\nCuando las parejas se comprometen en matrimonio, están entrando en algo mucho más grande que ellos mismos. Están participando en una institución divina establecida en la creación y honrada a lo largo de la historia redentora. Esta verdad demanda nuestra atención, nuestro respeto y nuestro compromiso de todo corazón.\n\nLa profundidad de este principio solo puede captarse cuando entendemos el matrimonio desde la perspectiva de Dios. Él no es un observador distante de nuestras uniones sino un participante activo que diseñó el matrimonio para nuestro florecimiento y Su gloria. Cada aspecto del pacto matrimonial apunta más allá de sí mismo hacia realidades eternas.\n\nMientras te preparas para el matrimonio, medita profundamente en lo que "${title.es}" significa para tu relación. ¿Cómo esta verdad dará forma a las decisiones que tomes? ¿Cómo te guiará a través de las dificultades? ¿Cómo transformará tu entendimiento del compromiso?\n\nEl mundo ofrece muchas falsificaciones del matrimonio—arreglos basados en conveniencia, pasión o beneficio mutuo. Pero el diseño de Dios es algo completamente diferente. Es amor de pacto que refleja Su propio corazón fiel. Es compromiso sacrificial que refleja el amor de Cristo por la iglesia. Es fidelidad perdurable que testifica promesas eternas.\n\nNo te conformes con nada menos que el diseño de Dios. No dejes que las bajas expectativas del mundo se conviertan en tu estándar. Álzate al llamado que las Escrituras ponen ante ti, y construye un matrimonio que honre a Aquel que los unió.`
    };
  }
  return expositions[day];
}

function generateRealityCheckForDay(day: number, title: BilingualText): BilingualText {
  return {
    en: `Our culture has fundamentally distorted the truth of "${title.en}." We are bombarded with messages that contradict God's design, and many couples have absorbed these lies without even realizing it.\n\nThe world tells us that commitment is optional, that feelings determine faithfulness, and that we should always protect our own interests first. These messages sound reasonable to ears trained by a self-centered culture, but they are poison to marriage.\n\nConsider how different our assumptions are from Scripture's teaching. We expect marriage to make us happy; Scripture calls us to sacrifice. We demand that our needs be met; Scripture calls us to serve. We reserve the right to leave when things get hard; Scripture calls us to covenant faithfulness unto death.\n\nThe gap between cultural expectations and biblical truth is vast. Many couples enter marriage with assumptions shaped more by romantic comedies than by Scripture. They expect perpetual passion without any effort. They assume love will sustain itself without intentional nurture. They believe that if things get too difficult, divorce is always an option.\n\nThese lies have produced a generation of broken marriages. The divorce rate among Christians is barely distinguishable from the culture around us. This is not because God's design is flawed—it is because we have rejected His design in favor of the world's counterfeits.\n\nIt is time to confront these lies with truth. "${title.en}" is not a suggestion but a command. It is not an ideal to aspire to but a reality to live. God's design for marriage works, but only when we actually follow it rather than the broken patterns of the world around us.`,
    es: `Nuestra cultura ha distorsionado fundamentalmente la verdad de "${title.es}." Somos bombardeados con mensajes que contradicen el diseño de Dios, y muchas parejas han absorbido estas mentiras sin siquiera darse cuenta.\n\nEl mundo nos dice que el compromiso es opcional, que los sentimientos determinan la fidelidad, y que siempre debemos proteger nuestros propios intereses primero. Estos mensajes suenan razonables a oídos entrenados por una cultura egocéntrica, pero son veneno para el matrimonio.\n\nConsidera cuán diferentes son nuestras suposiciones de la enseñanza de las Escrituras. Esperamos que el matrimonio nos haga felices; las Escrituras nos llaman al sacrificio. Exigimos que nuestras necesidades sean satisfechas; las Escrituras nos llaman a servir. Nos reservamos el derecho de irnos cuando las cosas se ponen difíciles; las Escrituras nos llaman a la fidelidad del pacto hasta la muerte.\n\nLa brecha entre las expectativas culturales y la verdad bíblica es vasta. Muchas parejas entran al matrimonio con suposiciones formadas más por comedias románticas que por las Escrituras. Esperan pasión perpetua sin ningún esfuerzo. Asumen que el amor se mantendrá solo sin nutrición intencional. Creen que si las cosas se ponen muy difíciles, el divorcio siempre es una opción.\n\nEstas mentiras han producido una generación de matrimonios rotos. La tasa de divorcio entre cristianos es apenas distinguible de la cultura que nos rodea. Esto no es porque el diseño de Dios sea defectuoso—es porque hemos rechazado Su diseño en favor de las falsificaciones del mundo.\n\nEs hora de confrontar estas mentiras con la verdad. "${title.es}" no es una sugerencia sino un mandato. No es un ideal al que aspirar sino una realidad para vivir. El diseño de Dios para el matrimonio funciona, pero solo cuando realmente lo seguimos en lugar de los patrones rotos del mundo que nos rodea.`
  };
}

function generatePracticalImplicationsForDay(day: number, title: BilingualText): BilingualText {
  return {
    en: `Living out the truth of "${title.en}" requires daily intentionality. This is not a principle to be understood and then forgotten—it must be woven into the fabric of your daily life together.\n\nBegin by examining your assumptions. What expectations have you brought to this relationship that might conflict with Scripture's teaching? What cultural messages have you absorbed that need to be challenged? Take time together to identify these areas and commit to aligning your thinking with God's Word.\n\nDevelop specific practices that reinforce this principle. Build rhythms into your relationship that remind you of your commitment. These might include daily prayer together, regular conversations about your marriage, or weekly times of reflection on how well you are living out your vows.\n\nAddress areas of failure promptly. When you recognize that you have violated this principle—and you will—do not let it fester. Confess your failure to God and to each other. Seek forgiveness and recommit yourself to faithful living. The health of your marriage depends on your willingness to acknowledge failure and pursue reconciliation.\n\nSeek support from others. Find mentors who model this principle well. Join a community of couples who are committed to building marriages that honor God. Do not try to live this out in isolation—you need the wisdom and encouragement of others who are on the same journey.\n\nFinally, be patient with yourselves and each other. Growth takes time. You will not perfectly embody this principle overnight. But with consistent effort, the help of the Holy Spirit, and the support of your community, you can build a marriage that increasingly reflects God's design.`,
    es: `Vivir la verdad de "${title.es}" requiere intencionalidad diaria. Este no es un principio para entender y luego olvidar—debe tejerse en la tela de su vida diaria juntos.\n\nComienza examinando tus suposiciones. ¿Qué expectativas has traído a esta relación que podrían entrar en conflicto con la enseñanza de las Escrituras? ¿Qué mensajes culturales has absorbido que necesitan ser desafiados? Tómense tiempo juntos para identificar estas áreas y comprométanse a alinear su pensamiento con la Palabra de Dios.\n\nDesarrollen prácticas específicas que refuercen este principio. Construyan ritmos en su relación que les recuerden su compromiso. Estos podrían incluir oración diaria juntos, conversaciones regulares sobre su matrimonio, o tiempos semanales de reflexión sobre qué tan bien están viviendo sus votos.\n\nAborden las áreas de fracaso prontamente. Cuando reconozcan que han violado este principio—y lo harán—no dejen que se enconara. Confiesen su fracaso a Dios y el uno al otro. Busquen perdón y vuelvan a comprometerse a vivir fielmente. La salud de su matrimonio depende de su disposición a reconocer el fracaso y buscar la reconciliación.\n\nBusquen apoyo de otros. Encuentren mentores que modelen bien este principio. Únanse a una comunidad de parejas que están comprometidas a construir matrimonios que honren a Dios. No traten de vivir esto en aislamiento—necesitan la sabiduría y el ánimo de otros que están en el mismo camino.\n\nFinalmente, sean pacientes consigo mismos y el uno con el otro. El crecimiento toma tiempo. No encarnarán perfectamente este principio de la noche a la mañana. Pero con esfuerzo consistente, la ayuda del Espíritu Santo, y el apoyo de su comunidad, pueden construir un matrimonio que refleje cada vez más el diseño de Dios.`
  };
}

function generateClosingChargeForDay(day: number, title: BilingualText): BilingualText {
  return {
    en: `You stand at a threshold. Before you lies a path that will lead to either flourishing or failure. The choices you make now—the commitments you embrace, the truths you accept, the patterns you establish—will shape the rest of your lives together.\n\n"${title.en}" is not an abstract concept. It is a living truth that must be embodied in your relationship. It is a call to rise above the mediocrity of the world's expectations and build something that truly honors God.\n\nDo not be deceived by the ease with which others discard their marriages. Do not be swayed by voices that tell you commitment is optional or that your happiness is the ultimate goal. These lies have destroyed countless relationships, and they will destroy yours if you embrace them.\n\nInstead, anchor yourself in the truth of Scripture. Build your marriage on the solid rock of God's Word. Commit yourselves fully to His design, trusting that His ways are better than the world's ways.\n\nThe path before you will not be easy. Marriage requires sacrifice, patience, humility, and perseverance. There will be seasons of difficulty when you are tempted to give up. In those moments, remember your covenant. Remember the God who witnessed your vows. Remember that He is faithful, and He will give you the strength to be faithful as well.\n\nGo forth and build a marriage worthy of the name. Let your union be a testimony to the goodness of God and the power of covenant love. The world is watching. Your children will be watching. Most importantly, God is watching. Honor Him with your marriage.`,
    es: `Están en un umbral. Ante ustedes hay un camino que llevará ya sea al florecimiento o al fracaso. Las decisiones que tomen ahora—los compromisos que abracen, las verdades que acepten, los patrones que establezcan—darán forma al resto de sus vidas juntos.\n\n"${title.es}" no es un concepto abstracto. Es una verdad viva que debe encarnarse en su relación. Es un llamado a elevarse por encima de la mediocridad de las expectativas del mundo y construir algo que verdaderamente honre a Dios.\n\nNo se dejen engañar por la facilidad con que otros descartan sus matrimonios. No se dejen influenciar por voces que les dicen que el compromiso es opcional o que su felicidad es la meta última. Estas mentiras han destruido incontables relaciones, y destruirán la suya si las abrazan.\n\nEn cambio, ánclense en la verdad de las Escrituras. Construyan su matrimonio sobre la roca sólida de la Palabra de Dios. Comprométanse completamente a Su diseño, confiando en que Sus caminos son mejores que los caminos del mundo.\n\nEl camino ante ustedes no será fácil. El matrimonio requiere sacrificio, paciencia, humildad y perseverancia. Habrá temporadas de dificultad cuando estarán tentados a rendirse. En esos momentos, recuerden su pacto. Recuerden al Dios que presenció sus votos. Recuerden que Él es fiel, y les dará la fuerza para ser fieles también.\n\nVayan y construyan un matrimonio digno del nombre. Que su unión sea un testimonio de la bondad de Dios y el poder del amor de pacto. El mundo está observando. Sus hijos estarán observando. Más importante aún, Dios está observando. Hónrenlo con su matrimonio.`
  };
}

function generateReflectionQuestionsForDay(day: number, title: BilingualText): BilingualText[] {
  return [
    {
      en: `How does your current understanding of "${title.en}" differ from what Scripture teaches?`,
      es: `¿Cómo difiere tu entendimiento actual de "${title.es}" de lo que enseñan las Escrituras?`
    },
    {
      en: "What cultural messages about marriage have you absorbed that need to be challenged?",
      es: "¿Qué mensajes culturales sobre el matrimonio has absorbido que necesitan ser desafiados?"
    },
    {
      en: "How would your relationship change if you fully embraced this principle?",
      es: "¿Cómo cambiaría tu relación si abrazaras completamente este principio?"
    },
    {
      en: "What specific steps can you take this week to better live out this truth?",
      es: "¿Qué pasos específicos puedes tomar esta semana para vivir mejor esta verdad?"
    },
    {
      en: "Who can help hold you accountable to this commitment?",
      es: "¿Quién puede ayudarte a ser responsable de este compromiso?"
    }
  ];
}

function generatePracticeBoxForDay(day: number, title: BilingualText): BilingualText[] {
  return [
    {
      en: "Discuss together what this principle means for your specific relationship.",
      es: "Discutan juntos qué significa este principio para su relación específica."
    },
    {
      en: "Identify one area where you need to grow in living out this truth.",
      es: "Identifica un área donde necesitas crecer en vivir esta verdad."
    },
    {
      en: "Pray together, asking God to help you embody this principle in your marriage.",
      es: "Oren juntos, pidiendo a Dios que les ayude a encarnar este principio en su matrimonio."
    },
    {
      en: "Share this devotional's key insight with a mentor or accountability partner.",
      es: "Comparte la perspectiva clave de este devocional con un mentor o compañero de responsabilidad."
    }
  ];
}

export function getSayingIDoDevotional(day: number): SayingIDoEntry | undefined {
  return sayingIDoEntries.find(entry => entry.day === day);
}

export function getAllSayingIDoDevotionals(): SayingIDoEntry[] {
  return sayingIDoEntries;
}
